### ISSUE TITLE
Problems with Encounter and Oberservations

### ISSUE THREAD

**Issue by Goldkugel** [juliangruendner/pj7-data-extraction#3]
Dear Projectathon team,

we are trying to run the docker containers and are struggling with two issues:

1. Our encounters on the fhir server do not have any "type"-field. Therefore, if one filters by this field (in the script it filters by type="Einrichtungskontakt") the result will be always empty. Is there any possibility to solve this e.g. not filtering at all? 

2. Our observations have as a patient resource an identifier and not a URL. It seems that the script has a problem when it faces an observation which has an identifier as a resource. In this case, the resource object is not being set. Are we correct? Regarding this issue, we attached a screenshot which might be helpful to understand.
![image](https://user-images.githubusercontent.com/100677854/206181927-47e7051e-30cf-4a00-8b7b-6c3a8828a030.png)

Thank you for your help in advance. 

Best regards

AIIM Team of TUM Munich

**Comment by juliangruendner** [comment]
@Goldkugel: 

1. if the type "Einrichtungskontakt" is not set - it is not implemented correctly.
However you could adjust the data_extraction_config.json accordingly

2. We expect a reference to be set - if u are currently not setting a reference u should adjust your ETL jobs accordingly.

**Comment by RaffaelBild** [comment]
@juliangruendner Thank you very much for the fast reply!

Regarding point 1, I would like to add that the attribute `type` has the cardinality 0..*
(see https://simplifier.net/medizininformatikinitiative-modulfall/kontaktgesundheitseinrichtung)
and hence, it might be more robust to restrict the FHIR search query in the script to MII Encounter resources using the attribute `Encounter.meta.profile` rather than `Encounter.type`.

Regarding point 2, I would like to point out that the profile MII-Reference supports both references via the attributes `reference` and `identifier` (see https://simplifier.net/packages/de.medizininformatikinitiative.kerndatensatz.meta/1.0.3/files/319433).
In our ETL jobs, we set the `Observation.subject.reference` to the URL of the corresponding Patient resource whenever it has already been materialized on the FHIR Server. However, if not, we set the `Observation.subject.identifier` to a business identifier of the Patient that has yet to be loaded. I think both should be in accordance with the MII profile and it would be perfect if the script would just ignore those Observation resources that do not have `Observation.subject.reference` set. Is it feasible to implement this? That would be much appreciated.

Best regards
Raffael

**Comment by juliangruendner** [comment]
@RaffaelBild:
1. as mentioned above you can remove the encounter type from the query in the config:
https://github.com/juliangruendner/pj7-data-extraction/blob/main/data_extraction_config.json.default#L24

2. We will not support the reference by identifier for this projectathon

**Comment by Goldkugel** [comment]
Dear Julian, 

we do not need support for references by identifier. We would kindly ask you to modify slightly your script in such a way that references by identifiers are ignored. Would that be suitable?

Thank you for your help. 

Best

AIIM Team of TUM Munich

**Comment by juliangruendner** [comment]
@Goldkugel  - what do you mean by ignored - deleted from the resource in the pseudonymisation stage?

**Comment by Goldkugel** [comment]
It would be great if Observations which have identifiers as references are not processed any further and are not part of the result or any calculation in it.

**Comment by juliangruendner** [comment]
@Goldkugel  - only observations or any resources?

**Comment by Goldkugel** [comment]
Only observations.

**Comment by juliangruendner** [comment]
i think this would be a change very specific to your site.
I would recommend that you fork the repo and create your own version.

**Comment by juliangruendner** [comment]
@Goldkugel  - also be aware that this repo is deprecated:
for new version please see: https://github.com/medizininformatik-initiative/Projectathon7-VHF-DataExtraction
